# Prod environment remote state backend configuration
# Update `bucket` with the bucket name generated by the `bootstrap` process.
terraform {
  backend "s3" {
    bucket         = "infra-tfstate-backend-rfghsb"
    key            = "prod/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-state-locks"
    encrypt        = true
  }
}
